### ISSUE TITLE
How to Increase Font?

### ISSUE THREAD

**Issue by chobo2** [Wikiki/bulma-tooltip#27]
Hi

Is there a built in way to increase the font-size?

**Comment by Wikiki** [comment]
Hi,

There is not. I put it in my todolist 😉

**Comment by chobo2** [comment]
@Wikiki 

Do you have a suggested work around? I was looking of trying to increase the font through css but then the bubble got cut off.

**Comment by Wikiki** [comment]
Did you tried to set 👍 
```css
.tooltip &:hover &::before,
.tooltip &.is-tooltip-active &::before {
     font-size: 12px;
}
```
